---
- name: "update local apt repo."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes


- name: "remove stale dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies [nodejs and npm]."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


# ---
# - name: "update apt packages."
#   become: true
#   apt:
#     update_cache: yes

# - name: "upgrade packages"
#   become: true
#   apt:
#     upgrade: yes

# - name: "remove dependencies that are no longer required"
#   become: true
#   apt:
#     autoremove: yes

# - name: "install nodejs and npm"
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install n"
#   become: true
#   npm:
#     name: n
#     global: yes
#     production: yes

# - name: "install nodejs 13.8.0"
#   become: true
#   shell: n 13.8.0

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present









# ---
# - name: "update apt packages."
#   become: true
#   apt:
#     update_cache: yes
#     cache_valid_time: 86400

# - name: "upgrade packages"
#   become: true
#   apt:
#     upgrade: yes

# - name: Install the gpg key for nodejs LTS
#   apt_key:
#     url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
#     state: present
    
# - name: Install the nodejs LTS repos
#   become: yes
#   apt_repository:
#     repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
#     state: present
#     update_cache: yes

# - name: Install the nodejs
#   become: yes
#   apt:
#     name: nodejs
#     state: present

# - name: "install pm2"
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present